export const PAYLOAD_MAX_SIZE = 16368; // 16KB or 16368 bytes
export const HEADER_SIZE = 16; // 16 bytes
export const MAX_MESSAGE_SIZE = PAYLOAD_MAX_SIZE + HEADER_SIZE;
export const RESPONSE_SIZE = 1024;
export const MAX_PRIORITY = 99;
export const DEFAULT_PRIORITY = 0;
export const DEFAULT_VERSION = 15;
export const REPEATER_PORT = 5065;
export const DEFAULT_PORT = 5064;
export const ADDR_LIST = ["127.0.0.1"];

export const commands = {
  VERSION: 0,
  READ: 3,
  CLIENT_NAME: 20,
  HOST_NAME: 21,
  ECHO: 23,
  REPEATER_REGISTER: 24,
};

export const DBR_TYPES = {
  DBR_STRING: 0,
  DBR_INT: 1,
  DBR_SHORT: 1,
  DBR_FLOAT: 2,
  DBR_ENUM: 3,
  DBR_CHAR: 4,
  DBR_LONG: 5,
  DBR_DOUBLE: 6,
  DBR_STS_STRING: 7,
  DBR_STS_INT: 8,
  DBR_STS_SHORT: 8,
  DBR_STS_FLOAT: 9,
  DBR_STS_ENUM: 10,
  DBR_STS_CHAR: 11,
  DBR_STS_LONG: 12,
  DBR_STS_DOUBLE: 13,
  DBR_TIME_STRING: 14,
  DBR_TIME_INT: 15,
  DBR_TIME_SHORT: 15,
  DBR_TIME_FLOAT: 16,
  DBR_TIME_ENUM: 17,
  DBR_TIME_CHAR: 18,
  DBR_TIME_LONG: 19,
  DBR_TIME_DOUBLE: 20,
  DBR_GR_STRING: 21,
  DBR_GR_INT: 22,
  DBR_GR_SHORT: 22,
  DBR_GR_FLOAT: 23,
  DBR_GR_ENUM: 24,
  DBR_GR_CHAR: 25,
  DBR_GR_LONG: 26,
  DBR_GR_DOUBLE: 27,
  DBR_CTRL_STRING: 28,
  DBR_CTRL_INT: 29,
  DBR_CTRL_SHORT: 29,
  DBR_CTRL_FLOAT: 30,
  DBR_CTRL_ENUM: 31,
  DBR_CTRL_CHAR: 32,
  DBR_CTRL_LONG: 33,
  DBR_CTRL_DOUBLE: 34,
  DBR_PUT_ACKT: 35,
  DBR_PUT_ACKS: 36,
  DBR_STSACK_STRING: 37,
  DBR_CLASS_NAME: 38,
};
