name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
            deno-version: v2.x # Run with latest stable Deno.       
      - name: Lint
        run: deno lint
  format:
    runs-on: ubuntu-latest
    name: Run Prettier
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
            deno-version: v2.x # Run with latest stable Deno.
      - name: Format Check
        run: deno fmt --check